START_WALLET_BALANCE = 1000.00
OUR_PRODUCT  = "Наші товари"
EMPTY_PRODUCT = "Товари відсутні"
RETURN_TITLE = "Повернення"
RETURN_TITLE_EMPTY = "Повернення відсутні"
CART_TITLE = "Кошик"
CART_TITLE_EMPTY = "Кошик пустий"
PURCHASE_TITLE = "Історія покупок"
PURCHASE_TITLE_EMPTY = "Ви ще нічого не купували"
NO_MONEY = 'Недостатньо коштів на рахунку'
DURATION_LIMIT = 180
NO_RETURN = 'Товар повернути не можливо'