# Generated by Django 3.2.18 on 2023-02-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wallet_currency',
            field=models.CharField(choices=[('USD', 'долар США'), ('EUR', 'евро'), ('GBP', 'британські фунти'), ('UAH', 'гривня')], default='UAH', max_length=3),
        ),
    ]
