# Generated by Django 3.2.18 on 2023-02-25 12:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_user_wallet_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='purchase_date_user',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
