# Generated by Django 3.2.18 on 2023-02-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_purchase_purchase_date_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='return',
            name='product',
        ),
        migrations.RemoveField(
            model_name='return',
            name='quantity',
        ),
        migrations.AddField(
            model_name='return',
            name='is_notice',
            field=models.BooleanField(default=False),
        ),
    ]
