# Generated by Django 3.2.18 on 2023-02-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20230225_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
